---
title: "CCLHM00076 - História da América: colonização e resistência"
lang: "pt-BR"
format: 
  pdf:
    geometry: 
      - top=1cm
      - bottom=1cm
      - left=1cm
      - right=1cm
      - landscape
    fontsize: 12pt
  html:
    theme: united
---
# Cronograma de aulas

Prof Eric Brasil

Período: 2024.1

## Módulos

1. Sociedades Autóctones das Américas (Antes do século XV)
2. Conquistas e Resistências (XVI-XVII)
3. Escravidão africana nas Américas (XVI-XVIII)

## Cronograma

|Aula|Data   | Módulo | Tema                                                                                   | CH | OBS        |
|:--:|-------|:------:|----------------------------------------------------------------------------------------|:--:|------------|
| 1  | 07/08 | I      | Quais Américas? Apresentação e reflexões sobre a disciplina                            | 4  | Presencial |
| 2  | 14/08 | I      | Como a inteligência artificial "vê" nosso curso?                                       | 4  | Remota     |
| 3  | 21/08 | I      | Sociedades autóctones americanas antes do século XVI                                   | 4  | Presencial |
| 4  | 28/08 | I      | Expansão europeia nos séculos XV e XVI e a chegada na América.                         | 4  | Presencial |
| 5  | 04/09 | II     | As várias visões da conquista                                                          | 4  | Presencial |
| 6  | 11/09 | II     | Resistências, negociações e agência indígenas nos séculos XVI e XVII                   | 4  | Presencial |
| 7  | 18/09 | II     | Formação da sociedade colonial espanhola (XVI-XVIII)                                   | 4  | Presencial |
| 8  | 25/09 | II     | Prova escrita presencial                                                               | 4  | Presencial |
| 9  | 02/10 | III    | Tráfico transatlântico de africanos escravizados: história e historiografia            | 4  | Presencial |
| 10 | 09/10 | III    | A escravidão nas regiões Andina, Platina e Mexicana                                    | 4  | Presencial |
| 11 | 16/10 | III    | Atividade Remota                                                                       | 4  | Remota     |
| 12 | 23/10 | III    | Atividade Remota                                                                       | 4  | Remota     |
| 13 | 30/10 | III    | O Caribe, as colônias na América do Norte e o desenvolvimento do sistema de plantation | 4  | Presencial |
| 14 | 06/11 | III    | Lutas contra o cativeiro, lutas pela liberdade - parte 1                               | 4  | Presencial |
| 15 | 13/11 | III    | Lutas contra o cativeiro, lutas pela liberdade - parte 2                               | 4  | Presencial |
